spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5



  jpa:
    show-sql: false

logging:
  level:
    com.aimarket: INFO
    org.springframework.security: TRACE
    org.springframework.web: TRACE

stripe:
  mock: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
